Add removal script for snapshot removal
skyscrapers/terraform-rds pull request #24
Opened 2018-09-24 13:36 UTC by reyntjensw

I have added a cleanup script in order to remove old snapshots after a fixed amount of time

2018-09-24 13:40 UTC, SamClinckspoor requested changes

2018-09-24 13:40 UTC, SamClinckspoor commented on snapshot-replicator/functions/remove_snapshots.py
> +instances = ['frisket-production-api-rds01']
this shouldn't be hardcoded.

2018-09-24 13:40 UTC, SamClinckspoor commented on snapshot-replicator/functions/remove_snapshots.py
> +DURATION= 30
can you make this configurable?

2018-09-24 13:40 UTC, SamClinckspoor commented on snapshot-replicator/functions/remove_snapshots.py
> +                )
Can you add a newline at the end here

2018-09-24 13:48 UTC, SamClinckspoor commented on snapshot-replicator/functions/remove_snapshots.py
> +import argparse
you don't seem to be using this pakage

2018-09-25 09:18 UTC, SamClinckspoor approved these changes
small nitpick

2018-09-25 09:18 UTC, SamClinckspoor commented on snapshot-replicator/functions/create_snapshot.py
> +instances = os.environ['DB_INSTANCES']
can you update your code to either use all caps for env variables or all lowercase? atm its mixed with eg `SOURCE_REGION` and `instances`

2018-09-25 09:21 UTC, SamClinckspoor commented on snapshot-replicator/functions/shipper.py
> +import boto3
Can you fix indentation in this file? you are mixing 2 and 4 spaces

2018-09-25 09:21 UTC, SamClinckspoor commented on snapshot-replicator/functions/shipper.py
>              except botocore.exceptions.ClientError as e:
you removed the botocore package

2018-09-25 09:45 UTC, venturel approved these changes

2018-09-25 11:03 UTC, merged