Add backup_retention_period variable for teamleader rds read replica
skyscrapers/terraform-rds pull request #36
Opened 2019-07-11 12:07 UTC by YorickH

2019-07-15 09:00 UTC, duboisph submitted a review, later dismissed

2019-07-15 09:01 UTC, duboisph commented
LGTM, could you just update the documentation too please?

2019-07-15 09:03 UTC, duboisph requested changes
Just some small change needed + could you also update the README please?

2019-07-15 09:03 UTC, duboisph commented on rds-replica/variables.tf
> +  description = "How long do you want to keep RDS Slave backups"
You should also specify the type here (`number`)

2019-07-15 09:03 UTC, duboisph commented on rds-replica/variables.tf
> +  default     = "14"
No quotes needed for a `number`

2019-07-31 07:55 UTC, YorickH commented
@duboisph updated

2019-08-01 09:00 UTC, duboisph approved these changes

2019-08-01 09:14 UTC, iuriaranda requested changes
Can you also update the documentation in the README with the new variable?

2019-08-02 11:40 UTC, iuriaranda approved these changes
Great. Thanks!

2019-08-02 11:41 UTC, merged

2019-08-02 11:44 UTC, iuriaranda commented
Released in version 5.0.1

Thanks for the contribution 😉